<?php
/**
 * Created by PhpStorm.
 * User: mingyan
 * Date: 15/7/18
 * Time: 1:12 PM
 */

namespace Myan\Helloworld\Test\Unit\Controller\Index;


class IndexTest extends \PHPUnit\Framework\TestCase
{
  protected $controller;
  protected $resultJsonFactory;

  public function setUp()
  {

    $objectManager = new \Magento\Framework\TestFramework\Unit\Helper\ObjectManager($this);
    $jsonResult = $objectManager->getObject('Magento\Framework\Controller\Result\Json');

    $this->resultJsonFactory = $this->getMockBuilder('Magento\Framework\Controller\Result\JsonFactory')
      ->disableOriginalConstructor()
      ->getMock();

    $this->resultJsonFactory->method('create')->willReturn($jsonResult);

    $this->controller = $objectManager->getObject(
      '\Myan\Helloworld\Controller\Index\Index',
      ['resultJsonFactory' => $this->resultJsonFactory]
    );


    parent::setUp(); // TODO: Change the autogenerated stub
  }

  public function testIndex()
  {

    $result = $this->controller->execute();

    $this->assertInstanceOf('\Magento\Framework\Controller\Result\Json', $result);
  }

}